In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Column rename
renamed_columns = ['self_employed', 'company_size', 'tech_company', 'tech_role', 'mh_coverage',
                   'mh_coverage_awareness', 'mh_employer_discussion', 'mh_resources_provided', 'mh_anonimity',
                   'mh_medical_leave', 'mh_discussion_negative_impact', 'ph_discussion_negative_impact',
                   'mh_discussion_coworkers','mh_discussion_supervisors', 'mh_equal_ph',
                   'mh_observed_consequences_coworkers', 'mh_coverage_2', 'mh_online_resources',
                   'mh_dx_revealed_clients', 'mh_dx_revealed_clients_impact', 'mh_dx_revealed_coworkers',
                   'mh_coworkers_reveal_negative_impact','mh_product_impact', 'mh_product_impact_perceived',
                   'prev_employers', 'prev_mh_benefits', 'prev_mh_benefits_awareness','prev_mh_discussion',
                   'prev_mh_resources', 'prev_mh_anonimity', 'prev_mh_discuss_negative_consequences',
                   'prev_ph_discuss_negative_consequences','prev_mh_discussion_coworkers',
                   'prev_mh_discussion_supervisors', 'prev_mh_importance_employer', 'prev_mh_consequences_coworkers',
                   'future_ph_specification', 'why_why_not', 'future_mh_specification', 'why_why_not2',
                   'mh_hurt_on_career', 'mh_neg_view_coworkers','mh_sharing_friends_family',
                   'mh_bad_response_workplace', 'mh_for_others_bad_response_workplace', 'mh_family_history',
                   'mh_dx_past', 'mh_dx_current', 'yes_what_dx?', 'maybe_whats_your_dx', 'mh_dx_pro',
                   'yes_condition_dx', 'mh_sought_pro_tx', 'mh_eff_tx_impact_on_work', 'mh_not_eff_tx_impact_on_work',
                   'age', 'gender', 'country_live', 'live_us_state', 'country_work', 'work_us_state',
                   'work_position', 'remote']

In [3]:
df = pd.read_csv(Path('../resources/OSMI_MHIT_survey/2016_OSMI_MHIT.csv'),names=renamed_columns)
df

,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
0,Are you self-employed?,How many employees does your company or organi...,Is your employer primarily a tech company/orga...,Is your primary role within your company relat...,Does your employer provide mental health benef...,Do you know the options for mental health care...,Has your employer ever formally discussed ment...,Does your employer offer resources to learn mo...,Is your anonymity protected if you choose to t...,If a mental health issue prompted you to reque...,...,"If you have a mental health issue, do you feel...","If you have a mental health issue, do you feel...",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your wor...,Do you work remotely?
1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Not applicable to me,Not applicable to me,34,Female,United States of America,New York,United States of America,New York,Other,Sometimes
1430,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Often,56,MALE,United States of America,California,Afghanistan,NaN,Support,Sometimes
1431,0,100-500,1,NaN,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,...,Rarely,Sometimes,52,Male,United States of America,Georgia,United States of America,Georgia,Back-end Developer,Sometimes
1432,0,100-500,0,1,I don't know,I am not sure,No,Yes,I don't know,Somewhat difficult,...,Sometimes,Often,30,Female,United States of America,Nebraska,United States of America,Nebraska,DevOps/SysAdmin,Sometimes
1433,0,100-500,1,NaN,Yes,No,No,No,I don't know,Very difficult,...,Not applicable to me,Often,25,non-binary,Canada,NaN,Canada,NaN,Other,Sometimes

In [4]:
#data distribution
df.describe()

,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
count,1434,1147,1147,264,1147,1014,1147,1147,1147,1147,...,1434,1434,1434,1431,1434,841,1434,852,1434,1434
unique,3,7,3,3,5,4,4,4,4,7,...,6,6,54,71,54,48,54,49,265,4
top,0,26-100,1,1,Yes,No,No,No,I don't know,Somewhat easy,...,Not applicable to me,Often,30,Male,United States of America,California,United States of America,California,Back-end Developer,Sometimes
freq,1146,292,883,248,531,354,813,531,742,281,...,557,538,94,610,840,130,851,141,263,757

In [5]:
#data types and counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1434 entries, 0 to 1433
Data columns (total 63 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   self_employed                          1434 non-null   object
 1   company_size                           1147 non-null   object
 2   tech_company                           1147 non-null   object
 3   tech_role                              264 non-null    object
 4   mh_coverage                            1147 non-null   object
 5   mh_coverage_awareness                  1014 non-null   object
 6   mh_employer_discussion                 1147 non-null   object
 7   mh_resources_provided                  1147 non-null   object
 8   mh_anonimity                           1147 non-null   object
 9   mh_medical_leave                       1147 non-null   object
 10  mh_discussion_negative_impact          1147 non-null   object
 11  ph_discussion_negative_impact          1147 non-null   object
 12  mh_discussion_coworkers                1147 non-null   object
 13  mh_discussion_supervisors              1147 non-null   object
 14  mh_equal_ph                            1147 non-null   object
 15  mh_observed_consequences_coworkers     1147 non-null   object
 16  mh_coverage_2                          288 non-null    object
 17  mh_online_resources                    288 non-null    object
 18  mh_dx_revealed_clients                 288 non-null    object
 19  mh_dx_revealed_clients_impact          145 non-null    object
 20  mh_dx_revealed_coworkers               288 non-null    object
 21  mh_coworkers_reveal_negative_impact    288 non-null    object
 22  mh_product_impact                      288 non-null    object
 23  mh_product_impact_perceived            205 non-null    object
 24  prev_employers                         1434 non-null   object
 25  prev_mh_benefits                       1265 non-null   object
 26  prev_mh_benefits_awareness             1265 non-null   object
 27  prev_mh_discussion                     1265 non-null   object
 28  prev_mh_resources                      1265 non-null   object
 29  prev_mh_anonimity                      1265 non-null   object
 30  prev_mh_discuss_negative_consequences  1265 non-null   object
 31  prev_ph_discuss_negative_consequences  1265 non-null   object
 32  prev_mh_discussion_coworkers           1265 non-null   object
 33  prev_mh_discussion_supervisors         1265 non-null   object
 34  prev_mh_importance_employer            1265 non-null   object
 35  prev_mh_consequences_coworkers         1265 non-null   object
 36  future_ph_specification                1434 non-null   object
 37  why_why_not                            1096 non-null   object
 38  future_mh_specification                1434 non-null   object
 39  why_why_not2                           1127 non-null   object
 40  mh_hurt_on_career                      1434 non-null   object
 41  mh_neg_view_coworkers                  1434 non-null   object
 42  mh_sharing_friends_family              1434 non-null   object
 43  mh_bad_response_workplace              1345 non-null   object
 44  mh_for_others_bad_response_workplace   658 non-null    object
 45  mh_family_history                      1434 non-null   object
 46  mh_dx_past                             1434 non-null   object
 47  mh_dx_current                          1434 non-null   object
 48  yes_what_dx?                           569 non-null    object
 49  maybe_whats_your_dx                    323 non-null    object
 50  mh_dx_pro                              1434 non-null   object
 51  yes_condition_dx                       712 non-null    object
 52  mh_sought_pro_tx                       1434 non-null   object
 53  mh_eff_tx_impact_on_work               1434 non-null   object
 54  mh_not_eff_tx_impact_on_work           1434 non-null   object
 55  age                                    1434 non-null   object
 56  gender                                 1431 non-null   object
 57  country_live                           1434 non-null   object
 58  live_us_state                          841 non-null    object
 59  country_work                           1434 non-null   object
 60  work_us_state                          852 non-null    object
 61  work_position                          1434 non-null   object
 62  remote                                 1434 non-null   object
dtypes: object(63)
memory usage: 705.9+ KB

In [6]:
# Re-Code Gender
# recode 'male'
df['gender'].replace(to_replace = ['Male', 'male', 'Male ', 'M', 'm','man', 'Cis male', 'Male.',
                                   'male 9:1 female, roughly', 'Male (cis)', 'Man', 'Sex is male','cis male', 'Malr',
                                   'Dude', "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
                                   'mail', 'M|', 'Male/genderqueer', 'male ','Cis Male', 'Male (trans, FtM)',
                                   'cisdude', 'cis man', 'MALE'],
                     value='male', inplace = True)
# recode 'female'
df['gender'].replace(to_replace = ['Female', 'female', 'I identify as female.', 'female ','Female assigned at birth ',
                                   'F', 'Woman', 'fm', 'f', 'Cis female ', 'Transitioned, M2F',
                                   'Genderfluid (born female)', 'Female or Multi-Gender Femme', 'Female ', 'woman',
                                   'female/woman','Cisgender Female', 'fem',
                                   'Female (props for making this a freeform field, though)',' Female', 'Cis-woman',
                                   'female-bodied; no feelings about gender','AFAB', 'Transgender woman'],
                     value='female', inplace = True)
# recode for nonbinary (including NaN values)
df['gender'].replace(to_replace = ['Bigender', 'non-binary', 'Other/Transfeminine','Androgynous', 'Other',
                                   'nb masculine','none of your business', 'genderqueer', 'Human', 'Genderfluid',
                                   'Enby', 'genderqueer woman', 'mtf', 'Queer', 'Agender', 'Fluid','Nonbinary',
                                   'human', 'Unicorn', 'Genderqueer','Genderflux demi-girl',np.NaN],
                     value='nonbinary', inplace = True)

# verify sucessful coding
print(df['gender'].unique())

['What is your gender?' 'male' 'female' 'nonbinary']

In [7]:
# Drop unusable columns
# drop freeform answer columns
df.drop(['why_why_not', 'why_why_not2'], axis=1, inplace=True)

# drop columns with more than 75% null values
df.drop(['tech_role','mh_coverage_2', 'mh_online_resources','mh_dx_revealed_clients',
         'mh_coworkers_reveal_negative_impact','mh_product_impact','mh_product_impact_perceived',
         'maybe_whats_your_dx','mh_dx_revealed_clients_impact','mh_dx_revealed_coworkers'], axis=1, inplace=True)

In [8]:
#Determine number of null entries per column
total = df.isnull().sum().sort_values(ascending=False)
percent = df.isnull().sum()/df.isnull().count()
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(40)

                                       Total   Percent
yes_what_dx?                             865  0.603208
mh_for_others_bad_response_workplace     776  0.541144
yes_condition_dx                         722  0.503487
live_us_state                            593  0.413529
work_us_state                            582  0.405858
mh_coverage_awareness                    420  0.292887
company_size                             287  0.200139
mh_observed_consequences_coworkers       287  0.200139
mh_equal_ph                              287  0.200139
mh_discussion_supervisors                287  0.200139
mh_discussion_coworkers                  287  0.200139
mh_discussion_negative_impact            287  0.200139
mh_medical_leave                         287  0.200139
mh_anonimity                             287  0.200139
mh_resources_provided                    287  0.200139
mh_employer_discussion                   287  0.200139
mh_coverage                              287  0.200139
tech_company                             287  0.200139
ph_discussion_negative_impact            287  0.200139
prev_mh_consequences_coworkers           169  0.117852
prev_mh_importance_employer              169  0.117852
prev_mh_discussion_coworkers             169  0.117852
prev_mh_discussion_supervisors           169  0.117852
prev_mh_resources                        169  0.117852
prev_ph_discuss_negative_consequences    169  0.117852
prev_mh_discuss_negative_consequences    169  0.117852
prev_mh_anonimity                        169  0.117852
prev_mh_discussion                       169  0.117852
prev_mh_benefits_awareness               169  0.117852
prev_mh_benefits                         169  0.117852
mh_bad_response_workplace                 89  0.062064
country_work                               0  0.000000
country_live                               0  0.000000
gender                                     0  0.000000
age                                        0  0.000000
mh_not_eff_tx_impact_on_work               0  0.000000
mh_eff_tx_impact_on_work                   0  0.000000
work_position                              0  0.000000
mh_sought_pro_tx                           0  0.000000
self_employed                              0  0.000000

In [9]:
missing_data.tail(40)

                                       Total   Percent
mh_discussion_negative_impact            287  0.200139
mh_medical_leave                         287  0.200139
mh_anonimity                             287  0.200139
mh_resources_provided                    287  0.200139
mh_employer_discussion                   287  0.200139
mh_coverage                              287  0.200139
tech_company                             287  0.200139
ph_discussion_negative_impact            287  0.200139
prev_mh_consequences_coworkers           169  0.117852
prev_mh_importance_employer              169  0.117852
prev_mh_discussion_coworkers             169  0.117852
prev_mh_discussion_supervisors           169  0.117852
prev_mh_resources                        169  0.117852
prev_ph_discuss_negative_consequences    169  0.117852
prev_mh_discuss_negative_consequences    169  0.117852
prev_mh_anonimity                        169  0.117852
prev_mh_discussion                       169  0.117852
prev_mh_benefits_awareness               169  0.117852
prev_mh_benefits                         169  0.117852
mh_bad_response_workplace                 89  0.062064
country_work                               0  0.000000
country_live                               0  0.000000
gender                                     0  0.000000
age                                        0  0.000000
mh_not_eff_tx_impact_on_work               0  0.000000
mh_eff_tx_impact_on_work                   0  0.000000
work_position                              0  0.000000
mh_sought_pro_tx                           0  0.000000
self_employed                              0  0.000000
mh_dx_pro                                  0  0.000000
mh_dx_current                              0  0.000000
mh_dx_past                                 0  0.000000
mh_family_history                          0  0.000000
mh_sharing_friends_family                  0  0.000000
mh_neg_view_coworkers                      0  0.000000
mh_hurt_on_career                          0  0.000000
future_mh_specification                    0  0.000000
future_ph_specification                    0  0.000000
prev_employers                             0  0.000000
remote                                     0  0.000000

In [10]:
df.head()

,self_employed,company_size,tech_company,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,mh_discussion_negative_impact,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
0,Are you self-employed?,How many employees does your company or organi...,Is your employer primarily a tech company/orga...,Does your employer provide mental health benef...,Do you know the options for mental health care...,Has your employer ever formally discussed ment...,Does your employer offer resources to learn mo...,Is your anonymity protected if you choose to t...,If a mental health issue prompted you to reque...,Do you think that discussing a mental health d...,...,"If you have a mental health issue, do you feel...","If you have a mental health issue, do you feel...",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your wor...,Do you work remotely?
1,0,26-100,1,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,No,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,No,Yes,Yes,Yes,Yes,Somewhat easy,No,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,No,NaN,No,No,I don't know,Neither easy nor difficult,Maybe,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes

In [11]:
# Examining distribution of data
df['country_live'].value_counts()

United States of America        840
United Kingdom                  180
Canada                           78
Germany                          58
Netherlands                      48
Australia                        35
Sweden                           19
France                           16
Ireland                          15
Brazil                           10
Switzerland                      10
Russia                            9
India                             9
New Zealand                       9
Finland                           7
Bulgaria                          7
Denmark                           7
Belgium                           5
Italy                             5
Austria                           4
Poland                            4
Romania                           4
Spain                             4
South Africa                      4
Norway                            3
Chile                             3
Pakistan                          3
Czech Republic                    3
Colombia                          2
Estonia                           2
Lithuania                         2
Other                             2
Japan                             2
Israel                            2
Bosnia and Herzegovina            2
Afghanistan                       2
Mexico                            2
Serbia                            1
Bangladesh                        1
What country do you live in?      1
Slovakia                          1
Brunei                            1
Argentina                         1
Vietnam                           1
Hungary                           1
China                             1
Costa Rica                        1
Venezuela                         1
Iran                              1
Greece                            1
Taiwan                            1
Algeria                           1
Guatemala                         1
Ecuador                           1
Name: country_live, dtype: int64

In [12]:
# Selecting rows based on condition (countries with more than 30 responses)
df = df.loc[(df['country_live'] == 'United States of America') | (df['country_live'] == 'United Kingdom') | (df['country_live'] == 'Canada') | (df['country_live'] == 'Germany') | (df['country_live'] == 'Netherlands') | (df['country_live'] == 'Australia')]

In [13]:
# Examining self-employed data
df['self_employed'].value_counts()

0    1007
1     232
Name: self_employed, dtype: int64

In [14]:
# Remove self-employed respondents
df = df.loc[(df['self_employed'] == '0')]

In [15]:
df.head()

,self_employed,company_size,tech_company,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,mh_discussion_negative_impact,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
1,0,26-100,1,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,No,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,No,Yes,Yes,Yes,Yes,Somewhat easy,No,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,No,NaN,No,No,I don't know,Neither easy nor difficult,Maybe,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
5,0,6-25,0,Yes,Yes,No,No,No,Neither easy nor difficult,Yes,...,Sometimes,Sometimes,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes
6,0,More than 1000,1,Yes,I am not sure,No,Yes,Yes,Somewhat easy,Yes,...,Not applicable to me,Often,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes

In [16]:
# Add unique identifier column for use in database
df.insert(0, 'new_id', range(1, 1 + len(df)))
df

,new_id,self_employed,company_size,tech_company,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
1,1,0,26-100,1,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,2,0,6-25,1,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,3,0,6-25,1,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
5,4,0,6-25,0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes
6,5,0,More than 1000,1,Yes,I am not sure,No,Yes,Yes,Somewhat easy,...,Not applicable to me,Often,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,1003,0,100-500,1,I don't know,I am not sure,No,I don't know,I don't know,Somewhat easy,...,Rarely,Often,26,female,Canada,NaN,Canada,NaN,Other,Sometimes
1428,1004,0,500-1000,1,Yes,No,No,No,Yes,Somewhat easy,...,Rarely,Often,38,female,United States of America,Illinois,United States of America,Illinois,Support,Always
1431,1005,0,100-500,1,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,...,Rarely,Sometimes,52,male,United States of America,Georgia,United States of America,Georgia,Back-end Developer,Sometimes
1432,1006,0,100-500,0,I don't know,I am not sure,No,Yes,I don't know,Somewhat difficult,...,Sometimes,Often,30,female,United States of America,Nebraska,United States of America,Nebraska,DevOps/SysAdmin,Sometimes
1433,1007,0,100-500,1,Yes,No,No,No,I don't know,Very difficult,...,Not applicable to me,Often,25,nonbinary,Canada,NaN,Canada,NaN,Other,Sometimes

In [17]:
# Examining age data
df['age'].value_counts()

30     67
28     59
32     57
35     55
29     54
31     53
27     49
26     49
34     48
33     44
37     41
39     40
36     38
24     34
38     30
40     29
25     29
22     24
42     21
45     20
44     19
23     19
43     17
46     15
41     15
21     13
47     10
49      7
48      5
51      5
20      5
52      5
55      5
50      4
57      3
53      2
63      2
56      2
54      2
66      1
3       1
323     1
99      1
70      1
62      1
59      1
58      1
19      1
74      1
61      1
Name: age, dtype: int64

In [18]:
# Convert age to integer
df[["age"]] = df[["age"]].apply(pd.to_numeric)

In [19]:
# drop ages outside of 'realistic' range (<20 | >100)
# Get names of indexes for which column Age has value less than 20
indexNames = df[df['age'] < 20 ].index

# Delete these row indexes from dataFrame
df.drop(indexNames, inplace=True)

# Get names of indexes for which column Age has value greater than 100
indexNames = df[df['age'] > 99 ].index

# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)

In [20]:
# Examining age to prepare for binning
df['age'].describe()

count    1004.000000
mean       33.659363
std         8.086614
min        20.000000
25%        28.000000
50%        32.000000
75%        38.000000
max        99.000000
Name: age, dtype: float64

In [21]:
# Fill null values in age column with mean
df['age'].fillna(df['age'].mean(), inplace = True)

In [22]:
# Bin age values into 4 equal sized groupings of the data
pd.qcut(df['age'], q=4)

1         (38.0, 99.0]
2         (28.0, 32.0]
3         (32.0, 38.0]
5         (38.0, 99.0]
6         (38.0, 99.0]
             ...
1427    (19.999, 28.0]
1428      (32.0, 38.0]
1431      (38.0, 99.0]
1432      (28.0, 32.0]
1433    (19.999, 28.0]
Name: age, Length: 1004, dtype: category
Categories (4, interval[float64]): [(19.999, 28.0] < (28.0, 32.0] < (32.0, 38.0] < (38.0, 99.0]]

In [23]:
#create 4 bins (aka quartiles) and 10 bins (aka deciles) and store the results back in the original dataframe
df['quantile_age_1'] = pd.qcut(df['age'], q=4)
df['quantile_age_2'] = pd.qcut(df['age'], q=10, precision=0)

df.head()

,new_id,self_employed,company_size,tech_company,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote,quantile_age_1,quantile_age_2
1,1,0,26-100,1,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes,"(38.0, 99.0]","(37.0, 39.0]"
2,2,0,6-25,1,No,Yes,Yes,Yes,Yes,Somewhat easy,...,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never,"(28.0, 32.0]","(27.0, 29.0]"
3,3,0,6-25,1,No,NaN,No,No,I don't know,Neither easy nor difficult,...,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always,"(32.0, 38.0]","(37.0, 39.0]"
5,4,0,6-25,0,Yes,Yes,No,No,No,Neither easy nor difficult,...,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"
6,5,0,More than 1000,1,Yes,I am not sure,No,Yes,Yes,Somewhat easy,...,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"

In [24]:
df.isnull().any()

new_id                                   False
self_employed                            False
company_size                             False
tech_company                             False
mh_coverage                              False
mh_coverage_awareness                     True
mh_employer_discussion                   False
mh_resources_provided                    False
mh_anonimity                             False
mh_medical_leave                         False
mh_discussion_negative_impact            False
ph_discussion_negative_impact            False
mh_discussion_coworkers                  False
mh_discussion_supervisors                False
mh_equal_ph                              False
mh_observed_consequences_coworkers       False
prev_employers                           False
prev_mh_benefits                          True
prev_mh_benefits_awareness                True
prev_mh_discussion                        True
prev_mh_resources                         True
prev_mh_anonimity                         True
prev_mh_discuss_negative_consequences     True
prev_ph_discuss_negative_consequences     True
prev_mh_discussion_coworkers              True
prev_mh_discussion_supervisors            True
prev_mh_importance_employer               True
prev_mh_consequences_coworkers            True
future_ph_specification                  False
future_mh_specification                  False
mh_hurt_on_career                        False
mh_neg_view_coworkers                    False
mh_sharing_friends_family                False
mh_bad_response_workplace                 True
mh_for_others_bad_response_workplace      True
mh_family_history                        False
mh_dx_past                               False
mh_dx_current                            False
yes_what_dx?                              True
mh_dx_pro                                False
yes_condition_dx                          True
mh_sought_pro_tx                         False
mh_eff_tx_impact_on_work                 False
mh_not_eff_tx_impact_on_work             False
age                                      False
gender                                   False
country_live                             False
live_us_state                             True
country_work                             False
work_us_state                             True
work_position                            False
remote                                   False
quantile_age_1                           False
quantile_age_2                           False
dtype: bool

In [25]:
# create function to display percent and number of entries per column that are null values
def missing_zero_values_table(df):
    zero_val = (df == 0.00).astype(int).sum(axis=0)
    null_val = df.isnull().sum()
    
    null_val_percent = 100 * df.isnull().sum() / len(df)
    mz_table = pd.concat([zero_val, null_val, null_val_percent], axis=1)
    
    mz_table = mz_table.rename(columns = {0 : 'Zero Values', 1 : 'Missing Values', 2 : '% of Total Values'})
    mz_table['Total Zero Missing Values'] = mz_table['Zero Values'] + mz_table['Missing Values']
    mz_table['% Total Zero Missing Values'] = 100 * mz_table['Total Zero Missing Values'] / len(df)
    mz_table['Data Type'] = df.dtypes
    mz_table = mz_table[mz_table.iloc[:,1] != 0].sort_values('% of Total Values',
                                                             ascending=False).round(1)
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns and " + str(df.shape[0]) + " Rows.\n"
           "There are " + str(mz_table.shape[0]) + " columns that have missing values.")
    # mz_table.to_csv('../missing_and_zero_values.csv', index = False)
    return mz_table

missing_zero_values_table(df)

Your selected dataframe has 54 columns and 1004 Rows.
There are 18 columns that have missing values.

,Zero Values,Missing Values,% of Total Values,Total Zero Missing Values,% Total Zero Missing Values,Data Type
yes_what_dx?,0,584,58.2,584,58.2,object
mh_for_others_bad_response_workplace,0,547,54.5,547,54.5,object
yes_condition_dx,0,482,48.0,482,48.0,object
live_us_state,0,297,29.6,297,29.6,object
work_us_state,0,295,29.4,295,29.4,object
prev_mh_benefits,0,111,11.1,111,11.1,object
prev_mh_consequences_coworkers,0,111,11.1,111,11.1,object
prev_mh_importance_employer,0,111,11.1,111,11.1,object
prev_mh_discussion_supervisors,0,111,11.1,111,11.1,object
prev_mh_discussion_coworkers,0,111,11.1,111,11.1,object
prev_ph_discuss_negative_consequences,0,111,11.1,111,11.1,object
prev_mh_discuss_negative_consequences,0,111,11.1,111,11.1,object
prev_mh_anonimity,0,111,11.1,111,11.1,object
prev_mh_resources,0,111,11.1,111,11.1,object
prev_mh_discussion,0,111,11.1,111,11.1,object
prev_mh_benefits_awareness,0,111,11.1,111,11.1,object
mh_coverage_awareness,0,103,10.3,103,10.3,object
mh_bad_response_workplace,0,44,4.4,44,4.4,object

In [26]:
# rename df something more descriptive
OSMI_MHIT_mostly_clean_df = df

In [27]:
# inspect current state of dataframe
OSMI_MHIT_mostly_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1004 entries, 1 to 1433
Data columns (total 54 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   new_id                                 1004 non-null   int64
 1   self_employed                          1004 non-null   object
 2   company_size                           1004 non-null   object
 3   tech_company                           1004 non-null   object
 4   mh_coverage                            1004 non-null   object
 5   mh_coverage_awareness                  901 non-null    object
 6   mh_employer_discussion                 1004 non-null   object
 7   mh_resources_provided                  1004 non-null   object
 8   mh_anonimity                           1004 non-null   object
 9   mh_medical_leave                       1004 non-null   object
 10  mh_discussion_negative_impact          1004 non-null   object
 11  ph_discussion_negative_impact          1004 non-null   object
 12  mh_discussion_coworkers                1004 non-null   object
 13  mh_discussion_supervisors              1004 non-null   object
 14  mh_equal_ph                            1004 non-null   object
 15  mh_observed_consequences_coworkers     1004 non-null   object
 16  prev_employers                         1004 non-null   object
 17  prev_mh_benefits                       893 non-null    object
 18  prev_mh_benefits_awareness             893 non-null    object
 19  prev_mh_discussion                     893 non-null    object
 20  prev_mh_resources                      893 non-null    object
 21  prev_mh_anonimity                      893 non-null    object
 22  prev_mh_discuss_negative_consequences  893 non-null    object
 23  prev_ph_discuss_negative_consequences  893 non-null    object
 24  prev_mh_discussion_coworkers           893 non-null    object
 25  prev_mh_discussion_supervisors         893 non-null    object
 26  prev_mh_importance_employer            893 non-null    object
 27  prev_mh_consequences_coworkers         893 non-null    object
 28  future_ph_specification                1004 non-null   object
 29  future_mh_specification                1004 non-null   object
 30  mh_hurt_on_career                      1004 non-null   object
 31  mh_neg_view_coworkers                  1004 non-null   object
 32  mh_sharing_friends_family              1004 non-null   object
 33  mh_bad_response_workplace              960 non-null    object
 34  mh_for_others_bad_response_workplace   457 non-null    object
 35  mh_family_history                      1004 non-null   object
 36  mh_dx_past                             1004 non-null   object
 37  mh_dx_current                          1004 non-null   object
 38  yes_what_dx?                           420 non-null    object
 39  mh_dx_pro                              1004 non-null   object
 40  yes_condition_dx                       522 non-null    object
 41  mh_sought_pro_tx                       1004 non-null   object
 42  mh_eff_tx_impact_on_work               1004 non-null   object
 43  mh_not_eff_tx_impact_on_work           1004 non-null   object
 44  age                                    1004 non-null   int64
 45  gender                                 1004 non-null   object
 46  country_live                           1004 non-null   object
 47  live_us_state                          707 non-null    object
 48  country_work                           1004 non-null   object
 49  work_us_state                          709 non-null    object
 50  work_position                          1004 non-null   object
 51  remote                                 1004 non-null   object
 52  quantile_age_1                         1004 non-null   category
 53  quantile_age_2                         1004 non-null   category
dtypes: category(2), int64(2), object(50)
memory usage: 418.4+ KB

In [28]:
# inspect individual values of 'mh_coverage_awareness'
OSMI_MHIT_mostly_clean_df['mh_coverage_awareness'].value_counts()

I am not sure    309
Yes              297
No               295
Name: mh_coverage_awareness, dtype: int64

In [29]:
# fill null values in 'coverage awareness' with 'not sure'
OSMI_MHIT_mostly_clean_df['mh_coverage_awareness'].fillna('I am not sure', inplace = True)

In [30]:
# inspect values of 'mh_bad_response_workplace'
OSMI_MHIT_mostly_clean_df['mh_bad_response_workplace'].value_counts()

No                    424
Maybe/Not sure        241
Yes, I observed       174
Yes, I experienced    121
Name: mh_bad_response_workplace, dtype: int64

In [31]:
# fill null values in 'mh_bad_response_workplace' with 'not sure'
OSMI_MHIT_mostly_clean_df['mh_bad_response_workplace'].fillna('Maybe/Not sure', inplace = True)

In [32]:
# inspect values of 'live_us_state'
OSMI_MHIT_mostly_clean_df['live_us_state'].value_counts()

California              110
Illinois                 47
Michigan                 43
Minnesota                38
Texas                    37
New York                 35
Washington               35
Pennsylvania             30
Oregon                   27
Tennessee                27
Colorado                 21
Indiana                  21
Ohio                     21
North Carolina           20
Massachusetts            19
Florida                  16
Virginia                 15
Kansas                   14
Maryland                 13
Oklahoma                 12
Georgia                  11
Nebraska                 10
Missouri                 10
Wisconsin                 8
Utah                      6
New Hampshire             5
New Jersey                5
Iowa                      5
Maine                     5
Alabama                   4
Arizona                   4
Rhode Island              3
South Dakota              3
North Dakota              3
Vermont                   3
Connecticut               3
Idaho                     3
Louisiana                 2
Kentucky                  2
Nevada                    2
District of Columbia      2
Alaska                    2
Montana                   1
West Virginia             1
Delaware                  1
South Carolina            1
New Mexico                1
Name: live_us_state, dtype: int64

In [33]:
# fill null values in 'live_us_state' with 'none'
OSMI_MHIT_mostly_clean_df['live_us_state'].fillna('none', inplace = True)

# fill null values in 'work_us_state' with 'none'
OSMI_MHIT_mostly_clean_df['work_us_state'].fillna('none', inplace = True)

In [34]:
# inspect current state of dataframe
OSMI_MHIT_mostly_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1004 entries, 1 to 1433
Data columns (total 54 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   new_id                                 1004 non-null   int64
 1   self_employed                          1004 non-null   object
 2   company_size                           1004 non-null   object
 3   tech_company                           1004 non-null   object
 4   mh_coverage                            1004 non-null   object
 5   mh_coverage_awareness                  1004 non-null   object
 6   mh_employer_discussion                 1004 non-null   object
 7   mh_resources_provided                  1004 non-null   object
 8   mh_anonimity                           1004 non-null   object
 9   mh_medical_leave                       1004 non-null   object
 10  mh_discussion_negative_impact          1004 non-null   object
 11  ph_discussion_negative_impact          1004 non-null   object
 12  mh_discussion_coworkers                1004 non-null   object
 13  mh_discussion_supervisors              1004 non-null   object
 14  mh_equal_ph                            1004 non-null   object
 15  mh_observed_consequences_coworkers     1004 non-null   object
 16  prev_employers                         1004 non-null   object
 17  prev_mh_benefits                       893 non-null    object
 18  prev_mh_benefits_awareness             893 non-null    object
 19  prev_mh_discussion                     893 non-null    object
 20  prev_mh_resources                      893 non-null    object
 21  prev_mh_anonimity                      893 non-null    object
 22  prev_mh_discuss_negative_consequences  893 non-null    object
 23  prev_ph_discuss_negative_consequences  893 non-null    object
 24  prev_mh_discussion_coworkers           893 non-null    object
 25  prev_mh_discussion_supervisors         893 non-null    object
 26  prev_mh_importance_employer            893 non-null    object
 27  prev_mh_consequences_coworkers         893 non-null    object
 28  future_ph_specification                1004 non-null   object
 29  future_mh_specification                1004 non-null   object
 30  mh_hurt_on_career                      1004 non-null   object
 31  mh_neg_view_coworkers                  1004 non-null   object
 32  mh_sharing_friends_family              1004 non-null   object
 33  mh_bad_response_workplace              1004 non-null   object
 34  mh_for_others_bad_response_workplace   457 non-null    object
 35  mh_family_history                      1004 non-null   object
 36  mh_dx_past                             1004 non-null   object
 37  mh_dx_current                          1004 non-null   object
 38  yes_what_dx?                           420 non-null    object
 39  mh_dx_pro                              1004 non-null   object
 40  yes_condition_dx                       522 non-null    object
 41  mh_sought_pro_tx                       1004 non-null   object
 42  mh_eff_tx_impact_on_work               1004 non-null   object
 43  mh_not_eff_tx_impact_on_work           1004 non-null   object
 44  age                                    1004 non-null   int64
 45  gender                                 1004 non-null   object
 46  country_live                           1004 non-null   object
 47  live_us_state                          1004 non-null   object
 48  country_work                           1004 non-null   object
 49  work_us_state                          1004 non-null   object
 50  work_position                          1004 non-null   object
 51  remote                                 1004 non-null   object
 52  quantile_age_1                         1004 non-null   category
 53  quantile_age_2                         1004 non-null   category
dtypes: category(2), int64(2), object(50)
memory usage: 418.4+ KB

In [35]:
# export 'mostly cleaned' dataframe to csv file
# OSMI_MHIT_mostly_clean_df.to_csv('../resources/OSMI_MHIT_mostly_clean.csv', index = False)