In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Column rename
renamed_columns = ['self_employed', 'company_size', 'tech_company', 'tech_role', 'mh_coverage',
                  'mh_coverage_awareness', 'mh_employer_discussion', 'mh_resources_provided', 'mh_anonimity',
                  'mh_medical_leave', 'mh_discussion_negative_impact', 'ph_discussion_negative_impact', 'mh_discussion_coworkers',
                  'mh_discussion_supervisors', 'mh_equal_ph', 'mh_observed_consequences_coworkers', 'mh_coverage_2', 'mh_online_resources',
                  'mh_dx_revealed_clients', 'mh_dx_revealed_clients_impact', 'mh_dx_revealed_coworkers', 'mh_coworkers_reveal_negative_impact',
                  'mh_product_impact', 'mh_product_impact_perceived', 'prev_employers', 'prev_mh_benefits', 'prev_mh_benefits_awareness',
                  'prev_mh_discussion', 'prev_mh_resources', 'prev_mh_anonimity', 'prev_mh_discuss_negative_consequences', 'prev_ph_discuss_negative_consequences',
                  'prev_mh_discussion_coworkers', 'prev_mh_discussion_supervisors', 'prev_mh_importance_employer', 'prev_mh_consequences_coworkers',
                  'future_ph_specification', 'why_why_not', 'future_mh_specification', 'why_why_not2', 'mh_hurt_on_career', 'mh_neg_view_coworkers',
                  'mh_sharing_friends_family', 'mh_bad_response_workplace', 'mh_for_others_bad_response_workplace', 'mh_family_history',
                  'mh_dx_past', 'mh_dx_current', 'yes_what_dx?', 'maybe_whats_your_dx', 'mh_dx_pro',
                  'yes_condition_dx', 'mh_sought_pro_tx', 'mh_eff_tx_impact_on_work', 'mh_not_eff_tx_impact_on_work',
                  'age', 'gender', 'country_live', 'live_us_state', 'country_work', 'work_us_state', 'work_position', 'remote']

In [3]:
df = pd.read_csv(Path('mental-heath-in-tech-2016_20161114.csv'),names=renamed_columns)
df.head(20)

,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
0,Are you self-employed?,How many employees does your company or organi...,Is your employer primarily a tech company/orga...,Is your primary role within your company relat...,Does your employer provide mental health benef...,Do you know the options for mental health care...,Has your employer ever formally discussed ment...,Does your employer offer resources to learn mo...,Is your anonymity protected if you choose to t...,If a mental health issue prompted you to reque...,...,"If you have a mental health issue, do you feel...","If you have a mental health issue, do you feel...",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your wor...,Do you work remotely?
1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
5,0,6-25,0,1,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes
6,0,More than 1000,1,NaN,Yes,I am not sure,No,Yes,Yes,Somewhat easy,...,Not applicable to me,Often,42,Male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes
7,0,26-100,1,NaN,I don't know,No,No,No,I don't know,Somewhat easy,...,Not applicable to me,Not applicable to me,30,M,United States of America,Tennessee,United States of America,Tennessee,Back-end Developer,Sometimes
8,0,More than 1000,1,NaN,Yes,Yes,No,Yes,Yes,Very easy,...,Sometimes,Often,37,female,United States of America,Virginia,United States of America,Virginia,Dev Evangelist/Advocate|Back-end Developer,Always
9,0,26-100,0,1,I don't know,No,No,No,I don't know,Very difficult,...,Rarely,Often,44,Female,United States of America,California,United States of America,California,Support|Back-end Developer|One-person shop,Sometimes
10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Rarely,Often,30,Male,United States of America,Kentucky,United States of America,Kentucky,One-person shop|Front-end Developer|Back-end D...,Always
11,0,26-100,1,NaN,Yes,I am not sure,Yes,Yes,Yes,Very easy,...,Sometimes,Often,28,Male,United States of America,Oregon,United States of America,Oregon,Front-end Developer,Never
12,0,100-500,0,1,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,...,Never,Rarely,34,Male,United States of America,Pennsylvania,United States of America,Pennsylvania,Executive Leadership,Sometimes
13,0,100-500,1,NaN,Yes,I am not sure,No,No,Yes,Very easy,...,Rarely,Sometimes,30,Female,United States of America,New Jersey,United States of America,New Jersey,Supervisor/Team Lead|Dev Evangelist/Advocate|B...,Always
14,0,100-500,0,1,Yes,Yes,Yes,Yes,Yes,Somewhat easy,...,Not applicable to me,Sometimes,44,Male,Canada,NaN,Canada,NaN,DevOps/SysAdmin|Back-end Developer|Front-end D...,Sometimes
15,0,100-500,1,NaN,Yes,Yes,No,I don't know,Yes,Very easy,...,Sometimes,Sometimes,35,Male,United States of America,Georgia,United States of America,Georgia,Designer,Always
16,0,100-500,1,NaN,I don't know,No,No,I don't know,I don't know,Neither easy nor difficult,...,Rarely,Sometimes,52,m,United States of America,Oregon,United States of America,Oregon,Other|Executive Leadership,Sometimes
17,0,26-100,1,NaN,Not eligible for coverage / N/A,No,No,No,I don't know,Very difficult,...,Sometimes,Often,32,I identify as female.,Canada,NaN,Canada,NaN,Front-end Developer,Always
18,0,500-1000,1,NaN,No,No,No,No,I don't know,I don't know,...,Not applicable to me,Not applicable to me,34,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Never
19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Often,Often,25,female,United States of America,Washington,United States of America,Washington,One-person shop,Always

In [4]:
#data row count
print(df.shape)

(1434, 63)

In [5]:
#distribution of the data?
print(df.describe(include='all'))

       self_employed company_size tech_company tech_role mh_coverage  \
count           1434         1147         1147       264        1147
unique             3            7            3         3           5
top                0       26-100            1         1         Yes
freq            1146          292          883       248         531

       mh_coverage_awareness mh_employer_discussion mh_resources_provided  \
count                   1014                   1147                  1147
unique                     4                      4                     4
top                       No                     No                    No
freq                     354                    813                   531

        mh_anonimity mh_medical_leave  ... mh_eff_tx_impact_on_work  \
count           1147             1147  ...                     1434
unique             4                7  ...                        6
top     I don't know    Somewhat easy  ...     Not applicable to me
freq             742              281  ...                      557

       mh_not_eff_tx_impact_on_work   age gender              country_live  \
count                          1434  1434   1431                      1434
unique                            6    54     71                        54
top                           Often    30   Male  United States of America
freq                            538    94    610                       840

       live_us_state              country_work work_us_state  \
count            841                      1434           852
unique            48                        54            49
top       California  United States of America    California
freq             130                       851           141

             work_position     remote
count                 1434       1434
unique                 265          4
top     Back-end Developer  Sometimes
freq                   263        757

[4 rows x 63 columns]

In [6]:
#Pandas: What types of data do i have?
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1434 entries, 0 to 1433
Data columns (total 63 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   self_employed                          1434 non-null   object
 1   company_size                           1147 non-null   object
 2   tech_company                           1147 non-null   object
 3   tech_role                              264 non-null    object
 4   mh_coverage                            1147 non-null   object
 5   mh_coverage_awareness                  1014 non-null   object
 6   mh_employer_discussion                 1147 non-null   object
 7   mh_resources_provided                  1147 non-null   object
 8   mh_anonimity                           1147 non-null   object
 9   mh_medical_leave                       1147 non-null   object
 10  mh_discussion_negative_impact          1147 non-null   object
 11  ph_discussion_negative_impact          1147 non-null   object
 12  mh_discussion_coworkers                1147 non-null   object
 13  mh_discussion_supervisors              1147 non-null   object
 14  mh_equal_ph                            1147 non-null   object
 15  mh_observed_consequences_coworkers     1147 non-null   object
 16  mh_coverage_2                          288 non-null    object
 17  mh_online_resources                    288 non-null    object
 18  mh_dx_revealed_clients                 288 non-null    object
 19  mh_dx_revealed_clients_impact          145 non-null    object
 20  mh_dx_revealed_coworkers               288 non-null    object
 21  mh_coworkers_reveal_negative_impact    288 non-null    object
 22  mh_product_impact                      288 non-null    object
 23  mh_product_impact_perceived            205 non-null    object
 24  prev_employers                         1434 non-null   object
 25  prev_mh_benefits                       1265 non-null   object
 26  prev_mh_benefits_awareness             1265 non-null   object
 27  prev_mh_discussion                     1265 non-null   object
 28  prev_mh_resources                      1265 non-null   object
 29  prev_mh_anonimity                      1265 non-null   object
 30  prev_mh_discuss_negative_consequences  1265 non-null   object
 31  prev_ph_discuss_negative_consequences  1265 non-null   object
 32  prev_mh_discussion_coworkers           1265 non-null   object
 33  prev_mh_discussion_supervisors         1265 non-null   object
 34  prev_mh_importance_employer            1265 non-null   object
 35  prev_mh_consequences_coworkers         1265 non-null   object
 36  future_ph_specification                1434 non-null   object
 37  why_why_not                            1096 non-null   object
 38  future_mh_specification                1434 non-null   object
 39  why_why_not2                           1127 non-null   object
 40  mh_hurt_on_career                      1434 non-null   object
 41  mh_neg_view_coworkers                  1434 non-null   object
 42  mh_sharing_friends_family              1434 non-null   object
 43  mh_bad_response_workplace              1345 non-null   object
 44  mh_for_others_bad_response_workplace   658 non-null    object
 45  mh_family_history                      1434 non-null   object
 46  mh_dx_past                             1434 non-null   object
 47  mh_dx_current                          1434 non-null   object
 48  yes_what_dx?                           569 non-null    object
 49  maybe_whats_your_dx                    323 non-null    object
 50  mh_dx_pro                              1434 non-null   object
 51  yes_condition_dx                       712 non-null    object
 52  mh_sought_pro_tx                       1434 non-null   object
 53  mh_eff_tx_impact_on_work               1434 non-null   object
 54  mh_not_eff_tx_impact_on_work           1434 non-null   object
 55  age                                    1434 non-null   object
 56  gender                                 1431 non-null   object
 57  country_live                           1434 non-null   object
 58  live_us_state                          841 non-null    object
 59  country_work                           1434 non-null   object
 60  work_us_state                          852 non-null    object
 61  work_position                          1434 non-null   object
 62  remote                                 1434 non-null   object
dtypes: object(63)
memory usage: 705.9+ KB
None

In [7]:
# Re-Code Gender
df['gender'].replace(to_replace = ['Male', 'male', 'Male ', 'M', 'm','man', 'Cis male', 'Male.', 'male 9:1 female, roughly', 'Male (cis)', 'Man', 'Sex is male','cis male', 'Malr', 'Dude', "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",'mail', 'M|', 'Male/genderqueer', 'male ','Cis Male', 'Male (trans, FtM)','cisdude', 'cis man', 'MALE'], value='male', inplace = True)

df['gender'].replace(to_replace = ['Female', 'female', 'I identify as female.', 'female ','Female assigned at birth ', 'F', 'Woman', 'fm', 'f', 'Cis female ', 'Transitioned, M2F','Genderfluid (born female)', 'Female or Multi-Gender Femme', 'Female ', 'woman', 'female/woman','Cisgender Female', 'fem', 'Female (props for making this a freeform field, though)',' Female', 'Cis-woman', 'female-bodied; no feelings about gender','AFAB'], value='female', inplace = True)

df['gender'].replace(to_replace = ['Bigender', 'non-binary', 'Other/Transfeminine','Androgynous', 'Other', 'nb masculine','none of your business', 'genderqueer', 'Human', 'Genderfluid','Enby', 'genderqueer woman', 'mtf', 'Queer', 'Agender', 'Fluid','Nonbinary', 'human', 'Unicorn', 'Genderqueer','Genderflux demi-girl', 'Transgender woman'], value='trans', inplace = True)

In [8]:
print(df['gender'].unique())

['What is your gender?' 'male' 'female' 'trans' nan]

In [9]:
df.drop(['why_why_not', 'why_why_not2'], axis=1, inplace=True)

In [10]:
#missing data
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(40)

                                       Total   Percent
mh_dx_revealed_clients_impact           1289  0.898884
mh_product_impact_perceived             1229  0.857043
tech_role                               1170  0.815900
mh_product_impact                       1146  0.799163
mh_coverage_2                           1146  0.799163
mh_online_resources                     1146  0.799163
mh_coworkers_reveal_negative_impact     1146  0.799163
mh_dx_revealed_coworkers                1146  0.799163
mh_dx_revealed_clients                  1146  0.799163
maybe_whats_your_dx                     1111  0.774756
yes_what_dx?                             865  0.603208
mh_for_others_bad_response_workplace     776  0.541144
yes_condition_dx                         722  0.503487
live_us_state                            593  0.413529
work_us_state                            582  0.405858
mh_coverage_awareness                    420  0.292887
ph_discussion_negative_impact            287  0.200139
mh_observed_consequences_coworkers       287  0.200139
mh_equal_ph                              287  0.200139
mh_discussion_supervisors                287  0.200139
mh_discussion_coworkers                  287  0.200139
mh_medical_leave                         287  0.200139
mh_anonimity                             287  0.200139
company_size                             287  0.200139
tech_company                             287  0.200139
mh_coverage                              287  0.200139
mh_employer_discussion                   287  0.200139
mh_resources_provided                    287  0.200139
mh_discussion_negative_impact            287  0.200139
prev_mh_anonimity                        169  0.117852
prev_mh_discussion                       169  0.117852
prev_mh_benefits                         169  0.117852
prev_mh_benefits_awareness               169  0.117852
prev_mh_discuss_negative_consequences    169  0.117852
prev_mh_resources                        169  0.117852
prev_ph_discuss_negative_consequences    169  0.117852
prev_mh_discussion_coworkers             169  0.117852
prev_mh_discussion_supervisors           169  0.117852
prev_mh_importance_employer              169  0.117852
prev_mh_consequences_coworkers           169  0.117852

In [11]:
missing_data.tail(40)

                                       Total   Percent
mh_medical_leave                         287  0.200139
mh_anonimity                             287  0.200139
company_size                             287  0.200139
tech_company                             287  0.200139
mh_coverage                              287  0.200139
mh_employer_discussion                   287  0.200139
mh_resources_provided                    287  0.200139
mh_discussion_negative_impact            287  0.200139
prev_mh_anonimity                        169  0.117852
prev_mh_discussion                       169  0.117852
prev_mh_benefits                         169  0.117852
prev_mh_benefits_awareness               169  0.117852
prev_mh_discuss_negative_consequences    169  0.117852
prev_mh_resources                        169  0.117852
prev_ph_discuss_negative_consequences    169  0.117852
prev_mh_discussion_coworkers             169  0.117852
prev_mh_discussion_supervisors           169  0.117852
prev_mh_importance_employer              169  0.117852
prev_mh_consequences_coworkers           169  0.117852
mh_bad_response_workplace                 89  0.062064
gender                                     3  0.002092
remote                                     0  0.000000
prev_employers                             0  0.000000
work_position                              0  0.000000
country_work                               0  0.000000
country_live                               0  0.000000
age                                        0  0.000000
mh_not_eff_tx_impact_on_work               0  0.000000
mh_eff_tx_impact_on_work                   0  0.000000
mh_sought_pro_tx                           0  0.000000
mh_dx_pro                                  0  0.000000
mh_dx_current                              0  0.000000
mh_dx_past                                 0  0.000000
mh_family_history                          0  0.000000
mh_sharing_friends_family                  0  0.000000
mh_neg_view_coworkers                      0  0.000000
mh_hurt_on_career                          0  0.000000
future_mh_specification                    0  0.000000
future_ph_specification                    0  0.000000
self_employed                              0  0.000000

In [12]:
df.head()

,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
0,Are you self-employed?,How many employees does your company or organi...,Is your employer primarily a tech company/orga...,Is your primary role within your company relat...,Does your employer provide mental health benef...,Do you know the options for mental health care...,Has your employer ever formally discussed ment...,Does your employer offer resources to learn mo...,Is your anonymity protected if you choose to t...,If a mental health issue prompted you to reque...,...,"If you have a mental health issue, do you feel...","If you have a mental health issue, do you feel...",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your wor...,Do you work remotely?
1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes

In [13]:
# Examining distribution of data
df['country_live'].value_counts()

United States of America        840
United Kingdom                  180
Canada                           78
Germany                          58
Netherlands                      48
Australia                        35
Sweden                           19
France                           16
Ireland                          15
Switzerland                      10
Brazil                           10
Russia                            9
New Zealand                       9
India                             9
Denmark                           7
Bulgaria                          7
Finland                           7
Italy                             5
Belgium                           5
Romania                           4
South Africa                      4
Spain                             4
Poland                            4
Austria                           4
Czech Republic                    3
Chile                             3
Pakistan                          3
Norway                            3
Other                             2
Afghanistan                       2
Mexico                            2
Estonia                           2
Israel                            2
Japan                             2
Colombia                          2
Lithuania                         2
Bosnia and Herzegovina            2
Brunei                            1
Argentina                         1
Hungary                           1
Algeria                           1
Greece                            1
Ecuador                           1
Costa Rica                        1
Vietnam                           1
Serbia                            1
China                             1
Slovakia                          1
Taiwan                            1
Iran                              1
Venezuela                         1
Bangladesh                        1
Guatemala                         1
What country do you live in?      1
Name: country_live, dtype: int64

In [14]:
# Selecting rows based on condition (countries with more than 30 responses)
df = df.loc[(df['country_live'] == 'United States of America') | (df['country_live'] == 'United Kingdom') | (df['country_live'] == 'Canada') | (df['country_live'] == 'Germany') | (df['country_live'] == 'Netherlands') | (df['country_live'] == 'Australia')]

In [15]:
# Examining self-employed data
df['self_employed'].value_counts()

0    1007
1     232
Name: self_employed, dtype: int64

In [16]:
# selecting rows based on condition (restrict to people only employed in a company) 
df = df.loc[(df['self_employed'] == '0')]

In [17]:
df.head()

,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,mh_medical_leave,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,0,6-25,1,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
5,0,6-25,0,1,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes
6,0,More than 1000,1,NaN,Yes,I am not sure,No,Yes,Yes,Somewhat easy,...,Not applicable to me,Often,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes

In [18]:
# Add Unique Identifier Column
df.insert(0, 'new_id', range(1, 1 + len(df)))
df

,new_id,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,...,mh_eff_tx_impact_on_work,mh_not_eff_tx_impact_on_work,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote
1,1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
2,2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
3,3,0,6-25,1,NaN,No,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
5,4,0,6-25,0,1,Yes,Yes,No,No,No,...,Sometimes,Sometimes,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes
6,5,0,More than 1000,1,NaN,Yes,I am not sure,No,Yes,Yes,...,Not applicable to me,Often,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,1003,0,100-500,1,NaN,I don't know,I am not sure,No,I don't know,I don't know,...,Rarely,Often,26,female,Canada,NaN,Canada,NaN,Other,Sometimes
1428,1004,0,500-1000,1,NaN,Yes,No,No,No,Yes,...,Rarely,Often,38,female,United States of America,Illinois,United States of America,Illinois,Support,Always
1431,1005,0,100-500,1,NaN,Yes,Yes,Yes,Yes,I don't know,...,Rarely,Sometimes,52,male,United States of America,Georgia,United States of America,Georgia,Back-end Developer,Sometimes
1432,1006,0,100-500,0,1,I don't know,I am not sure,No,Yes,I don't know,...,Sometimes,Often,30,female,United States of America,Nebraska,United States of America,Nebraska,DevOps/SysAdmin,Sometimes
1433,1007,0,100-500,1,NaN,Yes,No,No,No,I don't know,...,Not applicable to me,Often,25,trans,Canada,NaN,Canada,NaN,Other,Sometimes

In [19]:
# Examining age data
df['age'].value_counts()

30     67
28     59
32     57
35     55
29     54
31     53
26     49
27     49
34     48
33     44
37     41
39     40
36     38
24     34
38     30
40     29
25     29
22     24
42     21
45     20
23     19
44     19
43     17
41     15
46     15
21     13
47     10
49      7
52      5
20      5
51      5
55      5
48      5
50      4
57      3
54      2
63      2
56      2
53      2
74      1
99      1
58      1
323     1
3       1
62      1
19      1
70      1
66      1
61      1
59      1
Name: age, dtype: int64

In [20]:
# Convert age to integer
df[["age"]] = df[["age"]].apply(pd.to_numeric)

In [21]:
#drop unrealistic ages such as those under age 16 and over age 100
# Get names of indexes for which column Age has value less than 20
indexNames = df[ df['age'] < 20 ].index
# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)
# Get names of indexes for which column Age has value greater than 100
indexNames = df[ df['age'] > 100 ].index
# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)

In [22]:
# Examining age to prepare for binning
df['age'].describe()

count    1004.000000
mean       33.659363
std         8.086614
min        20.000000
25%        28.000000
50%        32.000000
75%        38.000000
max        99.000000
Name: age, dtype: float64

In [23]:
#complete missing age with mean
df['age'].fillna(df['age'].median(), inplace = True)

In [24]:
#create 4 equal sized groupings of the data
pd.qcut(df['age'], q=4)

1         (38.0, 99.0]
2         (28.0, 32.0]
3         (32.0, 38.0]
5         (38.0, 99.0]
6         (38.0, 99.0]
             ...
1427    (19.999, 28.0]
1428      (32.0, 38.0]
1431      (38.0, 99.0]
1432      (28.0, 32.0]
1433    (19.999, 28.0]
Name: age, Length: 1004, dtype: category
Categories (4, interval[float64]): [(19.999, 28.0] < (28.0, 32.0] < (32.0, 38.0] < (38.0, 99.0]]

In [25]:
#create 4 bins (aka quartiles) and 10 bins (aka deciles) and store the results back in the original dataframe
df['quantile_age_1'] = pd.qcut(df['age'], q=4)
df['quantile_age_2'] = pd.qcut(df['age'], q=10, precision=0)

df.head()

,new_id,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,...,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote,quantile_age_1,quantile_age_2
1,1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes,"(38.0, 99.0]","(37.0, 39.0]"
2,2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,...,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never,"(28.0, 32.0]","(27.0, 29.0]"
3,3,0,6-25,1,NaN,No,NaN,No,No,I don't know,...,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always,"(32.0, 38.0]","(37.0, 39.0]"
5,4,0,6-25,0,1,Yes,Yes,No,No,No,...,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"
6,5,0,More than 1000,1,NaN,Yes,I am not sure,No,Yes,Yes,...,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"

In [26]:
 df.isnull().any()

new_id            False
self_employed     False
company_size      False
tech_company      False
tech_role          True
                  ...
work_us_state      True
work_position     False
remote            False
quantile_age_1    False
quantile_age_2    False
Length: 64, dtype: bool

In [27]:
def missing_zero_values_table(df):
        zero_val = (df == 0.00).astype(int).sum(axis=0)
        mis_val = df.isnull().sum()
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        mz_table = pd.concat([zero_val, mis_val, mis_val_percent], axis=1)
        mz_table = mz_table.rename(
        columns = {0 : 'Zero Values', 1 : 'Missing Values', 2 : '% of Total Values'})
        mz_table['Total Zero Missing Values'] = mz_table['Zero Values'] + mz_table['Missing Values']
        mz_table['% Total Zero Missing Values'] = 100 * mz_table['Total Zero Missing Values'] / len(df)
        mz_table['Data Type'] = df.dtypes
        mz_table = mz_table[
            mz_table.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns and " + str(df.shape[0]) + " Rows.\n"      
            "There are " + str(mz_table.shape[0]) +
              " columns that have missing values.")
#         mz_table.to_excel('D:/sampledata/missing_and_zero_values.xlsx', freeze_panes=(1,0), index = False)
        return mz_table

missing_zero_values_table(df)

Your selected dataframe has 64 columns and 1004 Rows.
There are 29 columns that have missing values.

,Zero Values,Missing Values,% of Total Values,Total Zero Missing Values,% Total Zero Missing Values,Data Type
mh_coverage_2,0,1004,100.0,1004,100.0,object
mh_online_resources,0,1004,100.0,1004,100.0,object
mh_dx_revealed_clients,0,1004,100.0,1004,100.0,object
mh_dx_revealed_clients_impact,0,1004,100.0,1004,100.0,object
mh_dx_revealed_coworkers,0,1004,100.0,1004,100.0,object
mh_coworkers_reveal_negative_impact,0,1004,100.0,1004,100.0,object
mh_product_impact,0,1004,100.0,1004,100.0,object
mh_product_impact_perceived,0,1004,100.0,1004,100.0,object
maybe_whats_your_dx,0,790,78.7,790,78.7,object
tech_role,0,768,76.5,768,76.5,object
yes_what_dx?,0,584,58.2,584,58.2,object
mh_for_others_bad_response_workplace,0,547,54.5,547,54.5,object
yes_condition_dx,0,482,48.0,482,48.0,object
live_us_state,0,297,29.6,297,29.6,object
work_us_state,0,295,29.4,295,29.4,object
prev_mh_discuss_negative_consequences,0,111,11.1,111,11.1,object
prev_ph_discuss_negative_consequences,0,111,11.1,111,11.1,object
prev_mh_discussion_coworkers,0,111,11.1,111,11.1,object
prev_mh_discussion_supervisors,0,111,11.1,111,11.1,object
prev_mh_importance_employer,0,111,11.1,111,11.1,object
prev_mh_consequences_coworkers,0,111,11.1,111,11.1,object
prev_mh_resources,0,111,11.1,111,11.1,object
prev_mh_discussion,0,111,11.1,111,11.1,object
prev_mh_benefits_awareness,0,111,11.1,111,11.1,object
prev_mh_benefits,0,111,11.1,111,11.1,object
prev_mh_anonimity,0,111,11.1,111,11.1,object
mh_coverage_awareness,0,103,10.3,103,10.3,object
mh_bad_response_workplace,0,44,4.4,44,4.4,object
gender,0,3,0.3,3,0.3,object

In [28]:
df.drop(['mh_coverage_2', 'mh_online_resources','mh_dx_revealed_clients','mh_coworkers_reveal_negative_impact','mh_product_impact','mh_product_impact_perceived'], axis=1)

,new_id,self_employed,company_size,tech_company,tech_role,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,...,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote,quantile_age_1,quantile_age_2
1,1,0,26-100,1,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,39,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes,"(38.0, 99.0]","(37.0, 39.0]"
2,2,0,6-25,1,NaN,No,Yes,Yes,Yes,Yes,...,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never,"(28.0, 32.0]","(27.0, 29.0]"
3,3,0,6-25,1,NaN,No,NaN,No,No,I don't know,...,38,male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always,"(32.0, 38.0]","(37.0, 39.0]"
5,4,0,6-25,0,1,Yes,Yes,No,No,No,...,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"
6,5,0,More than 1000,1,NaN,Yes,I am not sure,No,Yes,Yes,...,42,male,United Kingdom,NaN,United Kingdom,NaN,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,1003,0,100-500,1,NaN,I don't know,I am not sure,No,I don't know,I don't know,...,26,female,Canada,NaN,Canada,NaN,Other,Sometimes,"(19.999, 28.0]","(25.0, 27.0]"
1428,1004,0,500-1000,1,NaN,Yes,No,No,No,Yes,...,38,female,United States of America,Illinois,United States of America,Illinois,Support,Always,"(32.0, 38.0]","(37.0, 39.0]"
1431,1005,0,100-500,1,NaN,Yes,Yes,Yes,Yes,I don't know,...,52,male,United States of America,Georgia,United States of America,Georgia,Back-end Developer,Sometimes,"(38.0, 99.0]","(44.0, 99.0]"
1432,1006,0,100-500,0,1,I don't know,I am not sure,No,Yes,I don't know,...,30,female,United States of America,Nebraska,United States of America,Nebraska,DevOps/SysAdmin,Sometimes,"(28.0, 32.0]","(29.0, 30.0]"
1433,1007,0,100-500,1,NaN,Yes,No,No,No,I don't know,...,25,trans,Canada,NaN,Canada,NaN,Other,Sometimes,"(19.999, 28.0]","(19.0, 25.0]"