In [10]:
import pandas as pd
from sqlalchemy import create_engine
from config1 import password
import psycopg2
import pandas.io.sql as sqlio

In [11]:
param_dic={
    "host": "mht.ciic7sa0kxc0.us-west-2.rds.amazonaws.com",
    "database": "postgres",
    "user" : "postgres",
    "password" : password
}

def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

conn = connect(param_dic)

Connecting to the PostgreSQL database...
Connection successful

In [12]:
# Import 2016 data:
query="SELECT * FROM survey_2016"
dataset_2016_df = sqlio.read_sql_query(query, conn)
dataset_2016_df.head()

,SurveyID,new_id,self_employed,company_size,tech_company,mh_coverage,mh_coverage_awareness,mh_employer_discussion,mh_resources_provided,mh_anonimity,...,age,gender,country_live,live_us_state,country_work,work_us_state,work_position,remote,quantile_age_1,quantile_age_2
0,2016,1,0,26-100,1,Not eligible for coverage / N/A,I am not sure,No,No,I don't know,...,39,male,United Kingdom,none,United Kingdom,none,Back-end Developer,Sometimes,"(38.0, 99.0]","(37.0, 39.0]"
1,2016,2,0,25-Jun,1,No,Yes,Yes,Yes,Yes,...,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never,"(28.0, 32.0]","(27.0, 29.0]"
2,2016,3,0,25-Jun,1,No,I am not sure,No,No,I don't know,...,38,male,United Kingdom,none,United Kingdom,none,Back-end Developer,Always,"(32.0, 38.0]","(37.0, 39.0]"
3,2016,4,0,25-Jun,0,Yes,Yes,No,No,No,...,43,female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"
4,2016,5,0,More than 1000,1,Yes,I am not sure,No,Yes,Yes,...,42,male,United Kingdom,none,United Kingdom,none,DevOps/SysAdmin|Support|Back-end Developer|Fro...,Sometimes,"(38.0, 99.0]","(39.0, 44.0]"

In [14]:
print(dataset_2016_df.columns.tolist())

['SurveyID', 'new_id', 'self_employed', 'company_size', 'tech_company', 'mh_coverage', 'mh_coverage_awareness', 'mh_employer_discussion', 'mh_resources_provided', 'mh_anonimity', 'mh_medical_leave', 'mh_discussion_negative_impact', 'ph_discussion_negative_impact', 'mh_discussion_coworkers', 'mh_discussion_supervisors', 'mh_equal_ph', 'mh_observed_consequences_coworkers', 'prev_employers', 'prev_mh_benefits', 'prev_mh_benefits_awareness', 'prev_mh_discussion', 'prev_mh_resources', 'prev_mh_anonimity', 'prev_mh_discuss_negative_consequences', 'prev_ph_discuss_negative_consequences', 'prev_mh_discussion_coworkers', 'prev_mh_discussion_supervisors', 'prev_mh_importance_employer', 'prev_mh_consequences_coworkers', 'future_ph_specification', 'future_mh_specification', 'mh_hurt_on_career', 'mh_neg_view_coworkers', 'mh_sharing_friends_family', 'mh_bad_response_workplace', 'mh_for_others_bad_response_workplace', 'mh_family_history', 'mh_dx_past', 'mh_dx_current', 'yes_what_dx?', 'mh_dx_pro', 'yes_condition_dx', 'mh_sought_pro_tx', 'mh_eff_tx_impact_on_work', 'mh_not_eff_tx_impact_on_work', 'age', 'gender', 'country_live', 'live_us_state', 'country_work', 'work_us_state', 'work_position', 'remote', 'quantile_age_1', 'quantile_age_2']